### ISSUE TITLE
Lag problem

### ISSUE THREAD

**Issue by Serios** [betterphp/NoFloatingTrees#8] opened 2012-06-22 11:28 UTC
My NoLagg stats showing huge lag spikes, here is my graph:
[IMG]http://i.imgur.com/gtizz.jpg[/IMG]

Apparently NoFloatingTrees lags more than AuthDB, which is using MySQL and is singe threaded.

**Comment by betterphp** [comment] 2012-06-22 12:02
Not somethign I have seen, could you check the size of your decay queue when this happens with /nftdebug ? It could be that the queue is building up quickly and since blocks don't decay if there are players nearby at the moment this causes a lot of useless random number generating and sqrt() calls. If that is the cause then it will be //fixed// when I have the blocks decay over time instead of suing the distance check.

I'll mark this as wontfix for now since I won't be addressing this issue directly, there is pretty much no fix anyway. But it will be improved in the future with the timed system.

Also note that I added the /nftpurge command which will force clear the entire queue in case the decay queue somehow grows to be very large.

**Closed as completed** 2012-06-22 12:02 UTC
Labels: wontfix
